# APPLICATION NAME
spring.application.name=expense-tracker

# DATABASE CONNECTION - via environment variables
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# JPA / HIBERNATE SETTINGS
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# SERVER PORT
server.port=${PORT:8080}

# JWT Configuration
jwt.secret=${JWT_SECRET}
jwt.expiration=86400000

spring.main.allow-circular-references=true